server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/liquibase
    username: postgres
    password: 123456
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    org.company.springliquibase: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] [%X{traceId}] [%X{spanId}] [%X{parentId}] %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] [%X{traceId}] [%X{spanId}] [%X{parentId}] %-5level %logger{36} - %msg%n"
  file:
    name: logs/spring-boot-logger.log